# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6629037686a60d8ddcaf97a7b2cc8b3e9a084e37fbd95dadef4de6678cd78bd333bfe49bc8b995e8676933c66436f51e081b0cd78f6110d753857bc0dcc353a1

test:
  secret_key_base: 2860cbfdef25c1a400cdc29685655d3c8ce1763cd873338e8b6c2bb81bd991872e9d1f7a391f4a52f43cd4bc7fd8b6dba974a027d2e476ecde3fdfdcd42e9a6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
